use_frameworks!

target 'HHUIKit_Example' do
  pod 'HHUIKit', :path => '../'

  target 'HHUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
